version: '3.8'

services:
  litterbox-api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - MONGODB_CONNECTION_STRING=${MONGODB_CONNECTION_STRING}
      - CHROMA_PERSIST_DIRECTORY=/app/data/chroma_db
      - LLM_MODEL=${LLM_MODEL:-gpt-4o-mini}
      - LLM_TEMPERATURE=${LLM_TEMPERATURE:-0.2}
      - DEFAULT_SCAFFOLDING_LEVEL=${DEFAULT_SCAFFOLDING_LEVEL:-2}
      - RETRIEVER_K=${RETRIEVER_K:-5}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - API_HOST=${API_HOST:-0.0.0.0}
      - API_PORT=${API_PORT:-8000}
    volumes:
      - ./data:/app/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

volumes:
  litterbox_data: